name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --file auth.dockerfile --tag containerssh-auth:latest .
      
    - name: Stop running Container
      run: |
        docker stop containerssh-backend
        docker container prune -f
        
    - name: Run New Image
      run: |
        docker run -p 5000:5000 --name containerssh-backend --restart always -d containerssh-auth:latest
        docker image prune -f
