name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file auth.dockerfile --tag containerssh-auth:latest
      
    - name: Stop running Container
      run: |
        docker stop container containerssh-backend
        docker container prune -f
        
    - name: Run New Image
      run: |
        docker run -p 5000:5000 containerssh-auth:latest
        docker image prune -f
